title: Hi! imvinipx
description: > # this means to ignore newlines until "baseurl:"
  Vinipx is a software quality engineer, people manager, and  speaker.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vinipx.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "https://twitter.com/imvinipx" #if your site has a twitter account, enter it here

# Author Settings
author: vinipx # add your name
author-img: vinipx.png # add your photo
about-author:  Software Quality Engineer <br> & <br> Career Manager # add description
social-twitter: imvinipx # add your Twitter handle
social-facebook: peixotofagundes # add your Facebook handle
social-github: vinipx # ig handle
social-linkedin: vinícius-fagundes-301b2429 # add your Linkedin handle
social-email: vinipeixotofagundes@gmail.com # add your Email address

# Disqus
discus-identifier: Vinipx # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
